# Copyright 2016 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
---
- name: Install jenkins.
  hosts: jenkins

  pre_tasks:
    - name: Configure yum for Jenkins repository.
      become: yes
      copy:
        src: jenkins/etc/yum.repos.d/jenkins.repo
        dest: /etc/yum.repos.d
      when: ansible_os_family == 'RedHat'

    - name: Configure apt for Jenkins repository.
      become: yes
      copy:
        src: jenkins/etc/apt/sources.list.d/jenkins.list
        dest: /etc/apt/sources.list.d
      when: ansible_os_family == 'Debian'

    - name: Configure gpg key for Jenkins repository.
      become: yes
      copy:
        src: jenkins/jenkins-ci.org.key
        dest: /etc/pki/rpm-gpg/
      when: ansible_os_family == 'RedHat'

    - name: Import GPG key for Jenkins repo.
      become: yes
      rpm_key:
        key: /etc/pki/rpm-gpg/jenkins-ci.org.key
      when: ansible_os_family == 'RedHat'

    - name: Import GPG key for Jenkins repo.
      become: yes
      apt_key:
        data: "{{ lookup('file', 'jenkins/jenkins-ci.org.key') }}"
      when: ansible_os_family == 'Debian'

    - name: Update apt cache.
      become: yes
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

  roles:
    - windmill.jenkins
    - windmill.ssh
    - windmill.jenkins-job-builder
    - windmill.jenkins-plugins
    - windmill.nginx

  tasks:
    # NOTE(pabelanger): Move this to ansible-role-jenkins-groovy
    - name: Copy groovy scripts into place.
      become: yes
      copy:
        dest: "{{ jenkins_user_home }}"
        group: "{{ jenkins_user_group }}"
        mode: 0444
        owner: "{{ jenkins_user_home }}"
        src: jenkins/var/lib/jenkins/init.groovy.d/
      notify: Restart jenkins

  post_tasks:
    - name: Check HTTP for jenkins
      delay: 10
      shell: "curl --head --silent http://{{ ansible_host }}/jenkins/"
      register: result
      retries: 3
      until: result.stdout.find('200 OK') != -1
      tags: skip_ansible_lint

  vars_files:
    - vars/jenkins.yaml
