# Copyright 2016 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
---
- name: Install nodepool-builder.
  hosts: nodepool-builder

  roles:
    - openstack.diskimage-builder
    - openstack.shade
    - openstack.nodepool

  pre_tasks:
    # NOTE(pabelanger): Move this to ansible-role-sudoers
    - name: Copy sudoers includes into place.
      become: yes
      copy:
        dest: /etc/sudoers.d/
        group: root
        mode: 0444
        owner: root
        src: nodepool/etc/sudoers.d/nodepool

    - name: Template disk-image-create wrapper script.
      become: yes
      template:
        dest: /usr/local/bin/disk-image-create
        group: root
        mode: 0755
        owner: root
        src: nodepool-builder/usr/local/bin/disk-image-create.j2

    # TODO(pabelanger): This should be moved into ansible-role-os-client-config.
    - name: Create os-client-config directories.
      become: yes
      file:
        group: root
        owner: root
        path: /etc/openstack
        state: directory

    - name: Copy clouds.yaml into place.
      become: yes
      copy:
        dest: /etc/openstack/clouds.yaml
        group: root
        mode: 0755
        owner: root
        src: nodepool/home/nodepool/.config/openstack/clouds.yaml

  post_tasks:
    - name: Run nodepool-server validation.
      include_role:
        name: test.nodepool-builder

  vars_files:
    - vars/nodepool.yaml
